# Generated by Django 5.2.17 on 2026-08-20 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('fraccion', models.CharField(choices=[('1.0', 'Día completo'), ('0.5', 'Medio día')], max_length=3, verbose_name='jornal')),
                ('tarea', models.CharField(blank=True, choices=[('plantacion', 'Plantación'), ('carpida', 'Carpida'), ('cultivada', 'Cultivada'), ('riego', 'Riego'), ('cosecha', 'Cosecha'), ('embolsado', 'Embolsado'), ('carga', 'Carga'), ('paleada', 'Paleada'), ('otro', 'Otro')], default='', max_length=30, verbose_name='tarea')),
                ('observacion', models.CharField(blank=True, default='', max_length=255, verbose_name='observación')),
                ('peon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjas', to='gestion.peon', verbose_name='peón')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Tarja',
                'verbose_name_plural': 'Tarjas',
                'ordering': ['-fecha', 'peon__nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('peon', 'fecha'), name='unique_tarja_activa_peon_fecha')],
            },
        ),
    ]
