# Generated by Django 5.2.17 on 2026-08-20 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tarja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cantidad_horas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)], verbose_name='cantidad de horas')),
                ('motivo', models.CharField(choices=[('riego', 'Riego'), ('cosecha', 'Cosecha'), ('fumigacion', 'Fumigación'), ('otro', 'Otro')], max_length=20, verbose_name='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('liquidada', 'Liquidada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('valor_jornal_aplicado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor del jornal aplicado')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor por hora')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('peon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras', to='gestion.peon', verbose_name='peón')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Hora extra',
                'verbose_name_plural': 'Horas extra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ValorJornal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor del jornal')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Valor del jornal',
                'verbose_name_plural': 'Valores del jornal',
                'ordering': ['-vigente_desde', '-id'],
            },
        ),
    ]
