# Generated by Django 5.2.17 on 2026-08-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_insumo_consumoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarja',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarjas_recibidas', to='gestion.peon', verbose_name='destinatario'),
        ),
        migrations.AddField(
            model_name='tarja',
            name='destino',
            field=models.CharField(choices=[('san_isidro', 'San Isidro'), ('externo', 'Externo')], default='san_isidro', max_length=20, verbose_name='destino'),
        ),
    ]
