# Generated by Django 5.2.17 on 2026-08-22 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_comprador_venta_pagoventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valorjornal',
            name='vigente_hasta',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='vigente hasta'),
        ),
        migrations.AlterField(
            model_name='valorjornal',
            name='vigente_desde',
            field=models.DateField(db_index=True, verbose_name='vigente desde'),
        ),
        migrations.AddConstraint(
            model_name='valorjornal',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gte', models.F('vigente_desde')), _connector='OR'), name='valor_jornal_vigencia_valida'),
        ),
    ]
