# Generated by Django 5.2.17 on 2026-08-24 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_valorjornal_vigente_hasta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornalCarpida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_jornada', models.CharField(choices=[('DIA', 'Día'), ('MEDIO_DIA', 'Medio día')], default='DIA', max_length=20, verbose_name='Tipo de jornada')),
                ('observacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Observación')),
                ('valor_jornal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor del jornal')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('liquidada', models.BooleanField(default=False, verbose_name='Liquidada')),
                ('peon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornales_carpida', to='gestion.peon', verbose_name='Peón')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Jornal de carpida',
                'verbose_name_plural': 'Jornales de carpida',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
