# Generated by Django 5.2.17 on 2026-08-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_jornalcarpida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalcarpida',
            name='peon',
        ),
    ]
