# Generated by Django 5.2.17 on 2026-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionalmacigo',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='liquidacionalmacigo',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación'),
        ),
        migrations.AddField(
            model_name='liquidacionalmacigo',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', verbose_name='motivo de anulación'),
        ),
        migrations.AddField(
            model_name='liquidacionpersonal',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='liquidacionpersonal',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación'),
        ),
        migrations.AddField(
            model_name='liquidacionpersonal',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', verbose_name='motivo de anulación'),
        ),
        migrations.AddField(
            model_name='liquidaciontractor',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='liquidaciontractor',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación'),
        ),
        migrations.AddField(
            model_name='liquidaciontractor',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', verbose_name='motivo de anulación'),
        ),
        migrations.AddField(
            model_name='rendicionventa',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='rendicionventa',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación'),
        ),
        migrations.AddField(
            model_name='rendicionventa',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', verbose_name='motivo de anulación'),
        ),
    ]
