# Generated by Django 5.2.17 on 2026-08-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_liquidacionpersonal_cuenta_financiera'),
        ('finanzas', '0004_movimientofinanciero_origen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidaciontractor',
            name='cuenta_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_tractor', to='finanzas.cuentafinanciera', verbose_name='cuenta financiera'),
        ),
    ]
