# Generated by Django 5.2.17 on 2026-08-25 13:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_rendicionventa_cuenta_financiera'),
        ('gestion', '0011_remove_jornalcarpida_peon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionpersonal',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total descuentos'),
        ),
        migrations.CreateModel(
            name='DetalleLiquidacionTarjaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('fraccion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='fracción de jornal')),
                ('valor_jornal_aplicado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor del jornal aplicado')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe descontado')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_tarjas_externas', to='administracion.liquidacionpersonal', verbose_name='liquidación')),
                ('peon_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_generados', to='gestion.peon', verbose_name='peón que trabajó')),
                ('tarja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_descuento_liquidacion', to='gestion.tarja', verbose_name='tarja externa')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'descuento por tarja externa',
                'verbose_name_plural': 'descuentos por tarjas externas',
                'ordering': ['fecha', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tarja',), name='unique_tarja_externa_descontada_activa')],
            },
        ),
    ]
