# Generated by Django 5.2.17 on 2026-08-26 05:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_liquidacionpersonal_total_descuentos_and_more'),
        ('gestion', '0012_alter_tarja_tarea_configuracionpaleada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionpersonal',
            name='total_administracion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total administración'),
        ),
        migrations.CreateModel(
            name='ValorAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cantidad_jornales', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad de jornales')),
                ('vigente_desde', models.DateField(db_index=True, verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, db_index=True, null=True, verbose_name='vigente hasta')),
                ('peon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vigencias_administrador', to='gestion.peon', verbose_name='administrador')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'valor administrador',
                'verbose_name_plural': 'valores administrador',
                'ordering': ['-vigente_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacionAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='mes')),
                ('cantidad_jornales', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad de jornales')),
                ('valor_jornal_aplicado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor jornal aplicado')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_administracion', to='administracion.liquidacionpersonal', verbose_name='liquidación')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('valor_administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='administracion.valoradministrador', verbose_name='configuración administrador')),
            ],
            options={
                'verbose_name': 'detalle liquidación administración',
                'verbose_name_plural': 'detalles liquidación administración',
                'ordering': ['anio', 'mes', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='valoradministrador',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gte', models.F('vigente_desde')), _connector='OR'), name='valor_administrador_vigencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='detalleliquidacionadministracion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('valor_administrador', 'anio', 'mes'), name='unique_administracion_mes_liquidada'),
        ),
    ]
