# Generated by Django 5.2.17 on 2026-09-14 14:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_liquidacionpersonal_total_administracion_and_more'),
        ('finanzas', '0006_alter_movimientofinanciero_tipo'),
        ('gestion', '0012_alter_tarja_tarea_configuracionpaleada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionCarpida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_desde', models.DateField(verbose_name='fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='fecha hasta')),
                ('fecha_pago', models.DateField(db_index=True, verbose_name='fecha de pago')),
                ('cantidad_carpidas', models.PositiveIntegerField(default=0, verbose_name='cantidad de carpidas')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='observación')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], db_index=True, default='ACTIVA', max_length=20, verbose_name='estado')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación')),
                ('motivo_anulacion', models.TextField(blank=True, default='', verbose_name='motivo de anulación')),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_carpidas', to='finanzas.cuentafinanciera', verbose_name='cuenta financiera')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'liquidación de carpidas',
                'verbose_name_plural': 'liquidaciones de carpidas',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacionCarpida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo_jornada', models.CharField(max_length=20, verbose_name='tipo de jornada')),
                ('valor_jornal_aplicado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor jornal aplicado')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='observación')),
                ('jornal_carpida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='gestion.jornalcarpida', verbose_name='jornal de carpida')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='administracion.liquidacioncarpida', verbose_name='liquidación')),
            ],
            options={
                'verbose_name': 'detalle de liquidación de carpida',
                'verbose_name_plural': 'detalles de liquidaciones de carpidas',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='liquidacioncarpida',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hasta__gte', models.F('fecha_desde'))), name='liquidacion_carpida_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='detalleliquidacioncarpida',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('jornal_carpida',), name='unique_jornal_carpida_liquidado_activo'),
        ),
    ]
