# Generated by Django 5.2.17 on 2026-08-24 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_categoriafinanciera_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoriafinanciera',
            name='unique_categoria_financiera_grupo',
        ),
        migrations.AddConstraint(
            model_name='categoriafinanciera',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nombre',), name='unique_categoria_financiera_'),
        ),
    ]
