# Generated by Django 5.2.17 on 2026-08-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_categoriafinanciera_unique_categoria_financiera_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='origen_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='origen_modulo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
