# Generated by Django 5.2.17 on 2026-08-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_movimientofinanciero_origen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentafinanciera',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos argentinos'), ('USD', 'Dólares estadounidenses')], db_index=True, default='ARS', max_length=3, verbose_name='Moneda'),
        ),
    ]
