# Generated by Django 5.2.17 on 2026-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_cuentafinanciera_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia'), ('CAMBIO_MONEDA', 'Cambio de moneda')], db_index=True, max_length=20, verbose_name='Tipo de movimiento'),
        ),
    ]
