# Generated by Django 5.2.17 on 2026-09-14 14:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_movimientofinanciero_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='monto_destino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto destino'),
        ),
    ]
